steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install','-DskipTests']
    dir: 'data-backend'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
    - 'apply'
    - '-f'
    - 'kubernetes.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
    dir: 'data-backend'
images: ['gcr.io/$PROJECT_ID/databackend']
