steps:
  - name: 'gcr.io/cloud-builders/mvn'
    id: Maven Build
    args: ['install','-DskipTests']
    dir: 'data-backend'
  - name: 'gcr.io/cloud-builders/mvn'
    id: Sonar Analysis
    args: ['sonar:sonar','-Dsonar.projectKey=celebrity-stock-exchange', '-Dsonar.host.url=http://35.195.53.92', '-Dsonar.login=1f32c1e43186674e060bf6343d236f55e2a4eced']
# Developer Edition is needed to run analysis on develop branch
#    args: ['sonar:sonar','-Dsonar.projectKey=celebrity-stock-exchange', '-Dsonar.branch.name=develop', '-Dsonar.host.url=http://35.195.53.92', '-Dsonar.login=1f32c1e43186674e060bf6343d236f55e2a4eced']
    dir: 'data-backend'
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/celebrity-stock-exchange/databackend:latest', '.']
    dir: 'data-backend'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
    - 'apply'
    - '-f'
    - 'kubernetes.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cex-cluster'
    dir: 'data-backend'
images: ['gcr.io/$PROJECT_ID/databackend']
