steps:
  - name: 'gcr.io/cloud-builders/mvn'
    id: Maven Build
    args: ['sonar:sonar','-Dsonar.projectKey=celebrity-stock-exchange','-Dsonar.host.url=http://34.76.132.85', '-Dsonar.login=8a0e479cbd0bae9bfc34a8f6595350487d8fa141']
    dir: 'data-backend'
  - name: 'gcr.io/cloud-builders/mvn'
    id: Sonar Analysis
    args: ['install','-DskipTests','-P build-docker-image']
    dir: 'data-backend'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
    - 'apply'
    - '-f'
    - 'kubernetes.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cex-cluster'
    dir: 'data-backend'
images: ['gcr.io/$PROJECT_ID/databackend']
