apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: cex-frontend
  name: cex-frontend
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cex-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cex-frontend
    spec:
      containers:
        - image: gcr.io/celebrity-stock-exchange/frontend:latest
          imagePullPolicy: Always
          name: frontend
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: cex-frontend-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: cex-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
