steps:
  # Install Angular
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install','-g','@angular/cli' ]
  # Install Dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # build Project in mode Prod.
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run','ng','build','']

images: ['gcr.io/$PROJECT_ID/stock-exchange']

