steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: Npm Install Angular (CLI)
    dir: 'stock-exchange'
    args: ['install','-g','@angular/cli' ]
  - name: 'gcr.io/cloud-builders/npm'
    id: Npm Install (Dependencies)
    dir: 'stock-exchange'
    args: ['install']
  - name: 'ubuntu'
    id: Set data-backend URL
    dir: 'stock-exchange'
    args: ['sed','-i','s/__DATABACKEND_URL__/${_DATA_BACKEND_URL_}/','src/environments/environment.prod.ts']
  - name: 'gcr.io/cloud-builders/npm'
    id: Npm lint
    dir: 'stock-exchange'
    args: ['run','ng','lint']
  - name: 'gcr.io/cloud-builders/npm'
    id: Npm Build --prod
    dir: 'stock-exchange'
    args: ['run','ng','build','--','--prod']
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', '.' ]
    dir: 'stock-exchange'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
      - 'apply'
      - '-f'
      - 'kubernetes.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cex-cluster'
    dir: 'stock-exchange'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Update-Image
    args:
      - 'set'
      - 'image'
      - 'deployment/cex-frontend'
      - 'frontend=gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cex-cluster'
    dir: 'stock-exchange'
images:
  - 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'
substitutions:
  _DATA_BACKEND_URL_: 'diva-e.com'
